# Generated by Django 5.0.4 on 2024-12-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_questions_attempted',
            field=models.IntegerField(default=0),
        ),
    ]
