# Generated by Django 5.0.4 on 2024-12-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_student_total_questions_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
